name: dl_tests
channels:
  - defaults
dependencies:
  - numpy
  - matplotlib
  - pyyaml=5.4.1
  - pillow
  - word2vec
  - tqdm
  - pip
  pip:
    - lmdb
    - torch
    - torchvision
    #- torchtext
