name: dl
channels:
  - defaults
  - pytorch
dependencies:
  - numpy
  - matplotlib
  - pyyaml
  - pillow
  - word2vec
  - tqdm
  - pytorch
  - torchvision
  - cudatoolkits=11.3
  - pip
  - pip:
    - lmdb
    #- torch
    #- torchvision
