Train:
  batch_size: 256
  learning_rate: 0.001
  reg: 0.00005
  epochs: 10
  steps: [6, 8]
  warmup: 0
  momentum: 0.9
  embed_dim: 1024
  num_classes: 1048
  train_percent: 0.1
  val_percent: 0.05
  semantic_reg: True
  cos_weight: 0.8
  image_weight: 0.1
  recipe_weight: 0.1
  workers: 4

network:
  model: im2recipe

data:
  data_path: 'data'
  image_path: 'data/images'
  generate_metrics: True
  save_best: False

ingredient_lstm:
  ingredient_lstm_dim: 300
  ingredient_embedding_dim: 300 # vocab size 30167 x 300 embedded
  ingredient_w2v_path: 'data/vocab.bin'

recipe_lstm:
  recipe_lstm_dim: 1024
  recipe_embedding_dim: 1024
