Train:
  batch_size: 256
  learning_rate: 0.0001
  epochs: 30
  embed_dim: 1024
  num_classes: 1048
  train_percent: 0.6
  val_percent: 0.2
  semantic_reg: False
  cos_weight: 0.98
  image_weight: 0.01
  recipe_weight: 0.01
  workers: 8
  mismatch: 0.5

network:
  model: im2recipe
  recipe_model: 'lstm' # lstm or transformer

data:
  data_path: '../data'
  image_path: '../images'
  generate_metrics: True
  metric_type: 'both' # rank or accuracy or both
  save_best: True

image_model:
  freeze_image: True

ingredient_lstm:
  ingredient_lstm_dim: 300
  ingredient_embedding_dim: 300 # vocab size 30167 x 300 embedded
  ingredient_w2v_path: '../data/vocab.bin'
  ingred_model_variant: 'paper' # base, custom_fusion, paper

recipe_lstm:
  recipe_lstm_dim: 1024
  recipe_embedding_dim: 1024
  recipe_model_variant: 'paper' # base, custom_basic, custom_fusion, paper
