Train:
  batch_size: 256
  learning_rate: 0.0001
  epochs: 10
  embed_dim: 1024
  num_classes: 1048
  train_percent: 0.6
  val_percent: 0.2
  semantic_reg: False
  cos_weight: 0.8
  image_weight: 0.1
  recipe_weight: 0.1
  workers: 4
  mismatch: 0.5

network:
  model: im2recipe
  recipe_model: 'lstm' # lstm or transformer

data:
  data_path: 'data'
  image_path: 'data/images'
  generate_metrics: True
  metric_type: 'both' # rank or accuracy or both
  save_best: False

image_model:
  freeze_image: True

ingredient_lstm:
  ingredient_lstm_dim: 300
  ingredient_embedding_dim: 300 # vocab size 30167 x 300 embedded
  ingredient_w2v_path: 'data/vocab.bin'
  ingred_model_variant: 'paper' # base, custom_basic, custom_fusion, paper
  #ingred_dropout: .2 

recipe_lstm:
  recipe_lstm_dim: 1024
  recipe_embedding_dim: 1024
  recipe_model_variant: 'paper' # base, custom_basic, custom_fusion, paper
  #recipe_dropout: .2

transformer:
    hidden_dim: 256
    num_heads: 4 # 2 original
    dim_feedforward: 256 # 2048 original
